services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:0.76.1
    env_file: .env
    networks:
      - internal
      - caddy
    ports:
      - 3000:3000
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - outline-postgres
      - outline-redis

  outline-redis:
    image: redis:7.2.5
    env_file: .env
    networks:
      - internal
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  outline-postgres:
    image: postgres:16.3
    env_file: .env
    networks:
      - internal
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "outline"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  https-portal-data:
  storage-data:
  database-data:

networks:
  internal:
    driver: bridge
  caddy:
    name: $CADDY_NETWORK
    external: true
