services:
  gitea:
    image: gitea/gitea:1.22.0
    restart: unless-stopped
    env_file: .env
    environment:
      USER_UID=1000
      USER_GID=1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: gitea-postgres:5432
      GITEA__database__NAME: ${POSTGRES_DB}
      GITEA__database__USER: ${POSTGRES_USER}
      GITEA__database__PASSWD: ${POSTGRES_PASSWORD}
    networks:
      - internal
      - caddy
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 222:22
    depends_on:
      - gitea-postgres
  
  gitea-postgres:
    image: postgres:16.3
    restart: unless-stopped
    env_file: .env
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  data:
    driver: local
  postgres:
    driver: local

networks:
  internal:
    driver: bridge
  caddy:
    name: $CADDY_NETWORK
    external: true
  